[project]
name = 'Decentralized-Waste-Management-Optimization-and-Recycling-Coordination-Network'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.circular-economy]
path = 'contracts/circular-economy.clar'
clarity_version = 2
epoch = 2.5

[contracts.composting-program]
path = 'contracts/composting-program.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
